roles/node_exporter/templates/node_exporter.service.j2
Set systemd's ProtectHome to 'read-only' instead of 'yes' if there exists filesystems which are mounted at or under '/home', instead of at '/home' exclusively.
Fixes #13.
Signed-off-by: Kevin Bowrin <kevinbowrin@cunet.carleton.ca>
=> node_exporter: Support filesystems mounted under '/home'

roles/node_exporter/tasks/preflight.yml
Use `ignore_errors` instead of warn parmeter. Fixes #9
=> node_exporter: Change command parameters for ansible 2.14 compatibility

.github/workflows/release.yml
Apparently when the `pull_request` trigger is used the workflow gets a read only github token, switching to `pull_request_target` should give writable token.
=> fix: use workflow trigger that gives writable token

.github/workflows/ansible-ci.yml, .github/workflows/conventional-label.yml, .github/workflows/release.yml
#29 and #30 didn't quite do the trick, this adds the required writable permissions to `pull_request_target` and also fixes triggers for workflows that got skipped after moving from `pull_request` to `pull_request_target`
Didn't catch these permission errors before since they were tested in my fork where I have write permissions, but now it's been tested in a separate fork where I gave myself restricted permissions.
=> fix: correct workflow triggers and writable permissions

requirements.yml, tests/integration/molecule.sh
Ansible galaxy frequently has timeout issues which makes the testing fail, we can limit the calls to galaxy by grabbing the collection dependencies directly from their git repos.
=> fix: grab dependencies from github to avoid galaxy timeouts

test-requirements.txt
- Fixes regression introduced in #26 where ansible 2.9, 2.10, 2.11 tests are failing due to `antsichaut` not being compatible with those python versions. (see: https://github.com/prometheus-community/ansible/actions/runs/4308763450)
- There is no need to install changelog tools when running collection tests, and removing them cuts down the time it takes to run the tests.
=> fix: avoid installing changelog tools when testing

.config/molecule/config.yml, test-requirements.txt
The linting is done as a separate CI job, so there is no need to spend time running ansible-lint each time molecule tests run.
And lint has been removed from molecule v5: https://github.com/ansible-community/molecule/pull/3802
=> removed: remove lint from molecule to avoid repetition

.github/workflows/release.yml
We need to use force push to update skipping the default branch protection rules.
=> fix: Force push git changelogs

tests/integration/molecule.sh
Workaround for installing collection requirements from git on ansible 2.9 since ansible 2.9 does not support that.
Fixes regression introduced in #33
=> fix: ansible 2.9 workaround for galaxy install from git

roles/prometheus/README.md, roles/prometheus/tasks/preflight.yml, test-requirements.txt
This is straightforward manipulation to do with standard Jinja features, there's no need to use a non-default library.
=> fix: Remove unnecessary dependency on jmespath

roles/alertmanager/README.md, roles/alertmanager/defaults/main.yml, roles/alertmanager/tasks/install.yml, roles/alertmanager/tasks/preflight.yml, roles/blackbox_exporter/README.md, roles/blackbox_exporter/defaults/main.yml, roles/blackbox_exporter/tasks/install.yml, roles/node_exporter/README.md, roles/node_exporter/defaults/main.yml, roles/node_exporter/tasks/install.yml, roles/node_exporter/tasks/preflight.yml, roles/prometheus/README.md, roles/prometheus/defaults/main.yml, roles/prometheus/tasks/install.yml, roles/prometheus/tasks/preflight.yml, roles/snmp_exporter/README.md, roles/snmp_exporter/defaults/main.yml, roles/snmp_exporter/tasks/install.yml, roles/snmp_exporter/tasks/preflight.yml
Allows grabbing binaries and checksums from a custom url/mirror, useful in closed environments where it's not possible to reach github.
=> feat: Allow grabbing binaries and checksums from a custom url/mirror

roles/alertmanager/meta/argument_specs.yml, roles/blackbox_exporter/meta/argument_specs.yml, roles/node_exporter/meta/argument_specs.yml, roles/prometheus/meta/argument_specs.yml, roles/snmp_exporter/meta/argument_specs.yml
Enables parameter validation in roles and opens up the possibility to auto generate docs with [antsibull-docs](https://github.com/ansible-community/antsibull-docs/)
=> docs: add argument specs to roles

.yamllint.yml, tests/integration/molecule.sh
Moved to standard path according to the [docs](https://yamllint.readthedocs.io/en/stable/configuration.html#default-configuration)
The [ansible/ansible-lint-action](https://github.com/ansible/ansible-lint-action) didn't pick up the yamllint cfg at the other path.
=> refactor: move yamllint cfg to standard path

.github/workflows/ansible-ci.yml, .gitignore
Fixes the issue where the ansible ci workflow didn't run on new commits / rebase in already open PR's, so problematic code can go undetected when added to already open PR's.
Also added pycache dirs to gitignore, these cache dirs get left behind when running molecule locally.
=> skip_changelog: Trigger test CI workflow on PR commits

roles/alertmanager/meta/argument_specs.yml, roles/blackbox_exporter/meta/argument_specs.yml, roles/node_exporter/meta/argument_specs.yml, roles/prometheus/defaults/main.yml, roles/prometheus/meta/argument_specs.yml, roles/prometheus/tasks/preflight.yml, roles/snmp_exporter/meta/argument_specs.yml
- Moves variables referenced from other variables out of tasks and into defaults.
- Adds missing argument specs for binary/checksum urls #28 
- Removes element validation from dict since it's only available on lists.
=> fix: various role argument specs

roles/alertmanager/tasks/preflight.yml, roles/alertmanager/templates/alertmanager.service.j2, roles/blackbox_exporter/tasks/preflight.yml, roles/blackbox_exporter/templates/blackbox_exporter.service.j2, roles/node_exporter/tasks/preflight.yml, roles/node_exporter/templates/node_exporter.service.j2, roles/prometheus/tasks/preflight.yml, roles/prometheus/templates/prometheus.service.j2
- Avoids using the command module and fragile regex parsing to get systemd version by getting systemd version from `package_facts`.
- This also removes the need for skipping the linting which caused the yaml linter to stop processing the rest of the preflight tasks, see bug: https://github.com/ansible/ansible-lint/issues/3139
=> refactor: avoid using command module for systemd version fact

.github/workflows/ansible-ci.yml
Avoid running ansible-ci workflow on push, since it doubles the number of executions for PRs built on in-repo branches.
=> skip_changelog: Don't run CI on push

roles/alertmanager/tasks/selinux.yml, roles/node_exporter/tasks/selinux.yml, roles/prometheus/vars/main.yml
I have a few legacy hosts with Centos 7 where trying to install python-policycoreutils fails.
At least in Centos 7 the packages is named policycoreutils-python, and finding no such package here either https://pkgs.org/download/python-policycoreutils
=> fix: policycoreutils python package name

.github/workflows/version_bumper.yml
The yq image is just yq. Use the prometheus golang-builder image to get a proper shell and yq.
=> skip_changelog: Use prom image for version script

roles/node_exporter/templates/node_exporter.service.j2
Correct the quotation around the collector option flags and values in the node_exporter role systemd unit config file template so that regex values get parsed correctly.
Refs: #68
=> fix: correct quotation of flags in systemd config file

roles/alertmanager/README.md, roles/alertmanager/defaults/main.yml, roles/alertmanager/meta/argument_specs.yml, roles/alertmanager/tasks/install.yml, roles/alertmanager/tasks/preflight.yml, roles/blackbox_exporter/README.md, roles/blackbox_exporter/defaults/main.yml, roles/blackbox_exporter/meta/argument_specs.yml, roles/blackbox_exporter/tasks/install.yml, roles/blackbox_exporter/tasks/preflight.yml, roles/mysqld_exporter/README.md, roles/mysqld_exporter/defaults/main.yml, roles/mysqld_exporter/meta/argument_specs.yml, roles/mysqld_exporter/tasks/install.yml, roles/mysqld_exporter/tasks/preflight.yml, roles/node_exporter/README.md, roles/node_exporter/defaults/main.yml, roles/node_exporter/meta/argument_specs.yml, roles/node_exporter/tasks/install.yml, roles/node_exporter/tasks/preflight.yml, roles/snmp_exporter/README.md, roles/snmp_exporter/defaults/main.yml, roles/snmp_exporter/meta/argument_specs.yml, roles/snmp_exporter/tasks/install.yml, roles/snmp_exporter/tasks/preflight.yml, roles/systemd_exporter/README.md, roles/systemd_exporter/defaults/main.yml, roles/systemd_exporter/meta/argument_specs.yml, roles/systemd_exporter/tasks/install.yml, roles/systemd_exporter/tasks/preflight.yml
This is similar to prometheus_skip_install variable and does what the name says: when set, it won't try to re-download alertmanager binaries
thanks for considering
=> enhancement: add `skip_install` variables to various roles

README.md, galaxy.yml, roles/alertmanager/README.md, roles/blackbox_exporter/README.md, roles/mysqld_exporter/README.md, roles/node_exporter/README.md, roles/prometheus/README.md, roles/snmp_exporter/README.md, roles/systemd_exporter/README.md
No need to maintain variable documentation in README when we got our online docs which are automatically generated.
=> docs: avoid maintaining variable documentation in many places

.github/workflows/ansible-test-integration.yml, roles/alertmanager/tasks/preflight.yml, roles/alertmanager/vars/main.yml, roles/mysqld_exporter/tasks/preflight.yml, roles/mysqld_exporter/vars/main.yml, roles/node_exporter/tasks/preflight.yml, roles/node_exporter/vars/main.yml, roles/prometheus/tasks/preflight.yml, roles/prometheus/vars/main.yml, roles/snmp_exporter/tasks/preflight.yml, roles/snmp_exporter/vars/main.yml, roles/systemd_exporter/tasks/preflight.yml, roles/systemd_exporter/vars/main.yml
Apparently the github api has a rate limit of 60 requests per hour for unauthenticated requests, but if we authenticate the requests with `GITHUB_TOKEN` from the CI we get 1000 requests per hour.
This PR passes the token to ansible, so we should see less failures in CI runs.
=> fix: pass token to github api for higher ratelimit

.config/molecule/config.yml, roles/alertmanager/README.md, roles/alertmanager/meta/main.yml, roles/blackbox_exporter/README.md, roles/blackbox_exporter/meta/main.yml, roles/mysqld_exporter/README.md, roles/mysqld_exporter/meta/main.yml, roles/node_exporter/README.md, roles/node_exporter/meta/main.yml, roles/prometheus/README.md, roles/prometheus/meta/main.yml, roles/snmp_exporter/README.md, roles/snmp_exporter/meta/main.yml, roles/systemd_exporter/meta/main.yml
- Drops support for EOL platforms (distros)
- Adds support for current (latest currently supported) platforms.
=> fix: replace eol platforms with current

roles/snmp_exporter/handlers/main.yml
=> fix: add "become: true" to snmp_exporter handlers

.config/ansible-lint.yml
This disables the linting rule `no-role-prefix` which got introduced in [ansible-lint v6.16.1](https://github.com/ansible/ansible-lint/releases/tag/v6.16.1). 
We prefer to use leading underscores to distinguish internal variables [as in python](https://peps.python.org/pep-0008/#descriptive-naming-styles) rather than prefixing them with the role name.
https://github.com/ansible/ansible-lint/pull/3422#issuecomment-1549584988
=> fix: don't require role name on internal vars

roles/systemd_exporter/meta/argument_specs.yml
This is a follow up to PR #102 .
=> docs: broken link to systemd exporter on docs

.github/scripts/version_updater.sh, .github/workflows/version_bumper.yml
* Check for remote branch before trying to build a changeset.
* Fail exit if push fails.
* Add pull-request permission to workflow.
=> skip_changelog: More fixes to version bumper

roles/node_exporter/tasks/configure.yml
Currently, if `basic_auth_users` is removed and neither `node_exporter_tls_server_config` nor `node_exporter_http_server_config` is defined, the users remain defined.
This is probably not intended behavior, since removing all the basic auth users ought to disable basic auth.
=> fix: always create config file

.github/scripts/version_updater.sh
DCO sign-off needs to be part of the commit, not required in the PR message.
=> skip_changelog: Fix version updater DCO

roles/mysqld_exporter/tasks/configure.yml
The mysqld_exporter config includes a MySQL user passsword and the web config may include htpasswd hashes. Don't allow everyone to peek them.
=> Fix mysqld_exporter world-readable secrets

roles/blackbox_exporter/defaults/main.yml, roles/blackbox_exporter/tasks/configure.yml, roles/blackbox_exporter/tasks/install.yml, roles/blackbox_exporter/templates/blackbox_exporter.service.j2
Also, binary and configuration owner is changed to root. User blackbox-exp should be prevented from modifying or deleting either the configuration or itself, according to the principle of least privilege.
=> feature: blackbox exporter user/group configurable

.github/workflows/ansible-ci.yml, .github/workflows/conventional-label.yml
Add the prefix `roles/` to the per-role label names in order to namespace them from other labels.
=> skip_changelog: Prefix role label triggers.

roles/alertmanager/defaults/main.yml
When i configuring alertmanager vars, the absence of 'routes' in front of '- match_re' has caused confusion and errors.
=> fix(alertmanager): add routes before match_re

tests/integration/molecule.sh
Temporarily avoid molecule 6 as seems to cause issues with our CI tests, probably caused by this: https://github.com/ansible/molecule/pull/3956
=> skip_changelog: temporarily pin molecule version

roles/node_exporter/molecule/latest/molecule.yml, roles/node_exporter/molecule/latest/tests/test_latest.py, roles/node_exporter/templates/node_exporter.service.j2
Set the node_exporter `ProtectHome=read-only` when the textfile dir is in `/home`.
Fixes: https://github.com/prometheus-community/ansible/issues/183
=> fix(node_exporter): Fix ProtectHome for textfiles

roles/blackbox_exporter/defaults/main.yml, roles/blackbox_exporter/handlers/main.yml, roles/blackbox_exporter/meta/argument_specs.yml, roles/blackbox_exporter/molecule/latest/molecule.yml, roles/blackbox_exporter/molecule/latest/tests/test_latest.py, roles/blackbox_exporter/tasks/configure.yml, roles/blackbox_exporter/tasks/install.yml, roles/blackbox_exporter/tasks/preflight.yml, roles/blackbox_exporter/vars/main.yml, roles/snmp_exporter/defaults/main.yml, roles/snmp_exporter/handlers/main.yml, roles/snmp_exporter/meta/argument_specs.yml, roles/snmp_exporter/molecule/latest/molecule.yml, roles/snmp_exporter/molecule/latest/tests/test_latest.py, roles/snmp_exporter/tasks/configure.yml, roles/snmp_exporter/tasks/install.yml, roles/snmp_exporter/tasks/preflight.yml, roles/snmp_exporter/vars/main.yml
Update the blackbox_exporter and snmp_exporter installs to be consistent with other exporter package installs.
Fixes: https://github.com/prometheus-community/ansible/issues/96
=> fix: Make binary installs consistent

roles/systemd_exporter/molecule/alternative/molecule.yml, roles/systemd_exporter/templates/systemd_exporter.service.j2
In systemd_exporter 0.5.0, `--systemd.collector` were renamed from `--collector` to `--systemd.collector`.
=> fix(systemd_exporter): Fix collector flags for older versions

roles/systemd_exporter/defaults/main.yml, roles/systemd_exporter/meta/argument_specs.yml, roles/systemd_exporter/templates/systemd_exporter.service.j2
Allow configuring the log verbosity of systemd_exporter via systemd_exporter_log_level, corresponding to the --log-level flag.
=> feat(systemd_exporter): Add logging configuration to systemd_exporter

.config/molecule/config.yml
I thought we had already avoided contacting the ansible galaxy api when switching requirements.yml over to git repos, but apparently molecule has a couple of ways it's installing dependencies, one which is controlled by the "dependency" key in the molecule config, and the other one that via the "prerun" option. The prerun uses ansible-compat and we can't pass any configuration to it, so the only option is to disable it.
By avoiding the galaxy api we can safely use older ansible versions which are incompatible with the ansible galaxy v3 api. 
This should also speed up testing a bit, since we're not installing dependencies multiple times per run.
=> fix(molecule): don't contact galaxy api since requirements come from git

.github/workflows/publish.yml
Perhaps a good idea to be able to publish manually in case the galaxy api is acting up.
=> skip_changelog: allow running publish workflow manually

test-requirements.txt, tests/integration/molecule.sh
Testinfra tests are failing on python 3.9 since testinfra v10.0.0.
https://github.com/prometheus-community/ansible/actions/runs/6906336970/job/18791174950
Seems to be caused by a old version of pytest already being installed on the ci image, this should update pytest and fix the issue.
=> skip_changelog(ci): make sure pytest and pytest-testinfra versions stay compatible

roles/blackbox_exporter/defaults/main.yml, roles/blackbox_exporter/molecule/alternative/tests/test_alternative.py, roles/blackbox_exporter/molecule/default/tests/test_default.py, roles/blackbox_exporter/tasks/configure.yml
Follow the pattern of other exporters and create the configuration file in `/etc/blackbox_exporter` by default.
=> feat(blackbox_exporter): Create config directory

roles/alertmanager/tasks/preflight.yml, roles/blackbox_exporter/tasks/preflight.yml, roles/chrony_exporter/tasks/preflight.yml, roles/mysqld_exporter/tasks/preflight.yml, roles/node_exporter/tasks/preflight.yml, roles/prometheus/tasks/preflight.yml, roles/pushgateway/tasks/preflight.yml, roles/smartctl_exporter/tasks/preflight.yml, roles/snmp_exporter/tasks/preflight.yml, roles/systemd_exporter/tasks/preflight.yml
Use the per-role repo var consistently in the preflight GitHub API URLs.
=> fix: Use repo var for preflight

changelogs/changelog.yaml
No idea how the actions managed to screw up the yaml formatting of the changelog in https://github.com/prometheus-community/ansible/commit/e0697b48c18928107ea5f4fe335a3e9a986e3223
=> skip_changelog: fix changelog indent

roles/mysqld_exporter/templates/my_cnf.j2
Modify the condition for `mysqld_exporter_host` in the mysqld_exporter my_cnf.j2 template to address an issue where `mysqld_exporter_host: null` in roles/defaults/main.yml was not being handled correctly. The updated condition ensures the host setting logic operates properly even when `mysqld_exporter_host` is set to null.
I also think a useful approach would be to simply remove mysqld_exporter_host[port] from defaults/main.yml and not change the template condition. I would appreciate your comments on this.
=> fix(mysqld_exporter): Change condition for mysqld_exporter_host check

roles/alertmanager/handlers/main.yml, roles/blackbox_exporter/handlers/main.yml, roles/prometheus/handlers/main.yml, roles/snmp_exporter/handlers/main.yml
Avoid triggering a reload of various role services when a restart is needed. This avoids the race between restart and reload.
=> fix: Don't reload services when restarting

roles/redis_exporter/README.md, roles/redis_exporter/defaults/main.yml, roles/redis_exporter/handlers/main.yml, roles/redis_exporter/meta/argument_specs.yml, roles/redis_exporter/meta/main.yml, roles/redis_exporter/molecule/alternative/molecule.yml, roles/redis_exporter/molecule/alternative/prepare.yml, roles/redis_exporter/molecule/alternative/tests/test_alternative.py, roles/redis_exporter/molecule/default/molecule.yml, roles/redis_exporter/molecule/default/tests/test_default.py, roles/redis_exporter/molecule/latest/molecule.yml, roles/redis_exporter/molecule/latest/tests/test_latest.py, roles/redis_exporter/tasks/configure.yml, roles/redis_exporter/tasks/install.yml, roles/redis_exporter/tasks/main.yml, roles/redis_exporter/tasks/preflight.yml, roles/redis_exporter/tasks/selinux.yml, roles/redis_exporter/templates/passwords.json.j2, roles/redis_exporter/templates/redis_exporter.service.j2, roles/redis_exporter/vars/main.yml, tests/integration/targets/molecule-redis_exporter-alternative/runme.sh, tests/integration/targets/molecule-redis_exporter-default/runme.sh, tests/integration/targets/molecule-redis_exporter-latest/runme.sh
Add new role: **redis_exporter**
=> feat: Add redis_exporter role

.github/scripts/discover_role_repos.sh, .github/scripts/version_updater.sh, .github/workflows/version_bumper.yml, roles/fail2ban_exporter/tasks/preflight.yml, roles/fail2ban_exporter/vars/main.yml
Support gitlab.com projects for `version_updater.sh`
@SuperQ as we discussed here #294 
Please, check this code, because I don't know how to test it myself completely.
My main idea was to keep code structure unchanged so much as possible.
=> skip_changelog(ci): gitlab.com support for version updater

roles/prometheus/defaults/main.yml, roles/prometheus/meta/argument_specs.yml, roles/prometheus/tasks/configure.yml, roles/prometheus/tasks/install.yml, roles/prometheus/templates/prometheus.service.j2
The use case is that when we want to deploy multiple Prometheus instances on the same host with different data directories. The current role have system user and group _hardcoded_ in the tasks and more over the Prometheus system user's home directory is set to Prometheus data directory.
When two different instances with two different data directories are deployed on the same instance, this will cause failures as we cannot change user's home directory while it is in use.
This PR simply adds the vars `prometheus_system_{user,group}` and set to `prometheus` and replace all instances of Prometheus user and group with variable references.
=> patch: Configurable Prometheus system user and group vars

roles/ipmi_exporter/templates/ipmi_exporter.service.j2
With the config before when systemd was above version 231 it was not allowed to create tmp files and with this change it now has the permissions to write tmp files.
Fixes #286
=> fix(ipmi_exporter): add option to impi_exporter service to allow tmp file creation

roles/mongodb_exporter/defaults/main.yml, roles/mongodb_exporter/templates/mongodb_exporter.service.j2
The collectors section within in the systemd service file checks if mongodb_exporter_collectors is iterable.
Since string is iterable the elif block does not trigger.
It results in:
```
ExecStart=/usr/local/bin/mongodb_exporter \
--collector.a \
--collector.l \
--collector.l \
--web.listen-address=0.0.0.0:9216 \
```
I have change the check to not look for `iterable` but explicit check for `list`
=> fix: change monogdb exporter collector check in service

.github/scripts/version_updater.sh
The command line parser for the verison updater was not updated to support the additional parameter.
* Rename `type` variable to `githost` to make it more clear.
=> skip_changelog: Fix version updater

roles/node_exporter/defaults/main.yml, roles/node_exporter/meta/argument_specs.yml, roles/node_exporter/templates/node_exporter.service.j2
Add ability to disable exporter metrics itself which is a long-lasting feature of node_exporter ([source code](https://github.com/prometheus/node_exporter/blame/3accd4cf8286e69d70516abdced6bf186274322a/node_exporter.go#L164)):
```bash
$ docker run -it quay.io/prometheus/node-exporter:latest --help | grep 'web.disable' -A1
--[no-]web.disable-exporter-metrics  
Exclude metrics about the exporter itself (promhttp_*, process_*, go_*).
```
=> enhancement: Add ability to disable exporter metrics itself

roles/mongodb_exporter/templates/mongodb_exporter.service.j2
According to cli options:
https://github.com/percona/mongodb_exporter/blob/main/REFERENCE.md
By default direct connect sets to `true`, but when `srv+` uri for mongodb is used (srv doesn not support direct connect) it's not possible to turn it off explicity, which results in error:
```
Mar 13 10:04:49 devops1 mongodb_exporter[569538]: level=info ts=2024-03-13T09:04:49.643Z caller=tls_config.go:274 msg="Listening on" address=[::]:9216
Mar 13 10:04:49 devops1 mongodb_exporter[569538]: level=info ts=2024-03-13T09:04:49.643Z caller=tls_config.go:277 msg="TLS is disabled." http2=false address=[::]:9216
Mar 13 10:04:49 devops1 mongodb_exporter[569538]: time="2024-03-13T10:04:49+01:00" level=error msg="Cannot connect to MongoDB: invalid MongoDB options: a direct connection cannot be made if …
```
=> bug: no ability to expilicitly set no direct connect and no global connection pool

.github/workflows/docs-pr.yml, .github/workflows/docs-push.yml
Removes GPL headers as requested: https://github.com/prometheus-community/ansible/pull/69#pullrequestreview-1874957858
It should be safe to remove the headers as the samples that these workflows are based on don't have the license headers.
https://github.com/ansible-community/github-docs-build/blob/c87c4e381fe8ef464e9d0318043ca1284af66b01/samples/pr-build-and-comment.yml
https://github.com/ansible-community/github-docs-build/blob/c87c4e381fe8ef464e9d0318043ca1284af66b01/samples/push-with-build.yml
=> skip_changelog: satisfy cncf license scanner

.config/ansible-lint.yml
Fix linting errors by downgrading the `name[casing]` check to warning.
=> fix: Downgrade name[casing] to warning

.github/workflows/docs-pr.yml, .github/workflows/docs-push.yml
Redirects the docs page to the docs for latest published version instead of the docs for the main branch which may contain unreleased features.
fixes #370
=> docs: redirect docs page to latest release instead of docs for upcoming release

.config/molecule/config.yml
Reached EOL 31 May 2024  
https://endoflife.date/centos-stream
=> removed: Drop centos 8 stream support as it is EOL

roles/prometheus/meta/argument_specs.yml
The prometheus configuration `storage.tsdb.retention` should be setted via `prometheus_storage_retention`. If setted via
`prometheus_config_flags_extra` it throws `duplicating configuration` error.
=> docs: fix config_flags_extra wrong example 

.github/scripts/version_updater.sh
Explicitly match the full version variable name to avoid matching other variables when updating the `defaults/main.yml` file.
=> skip_changelog: Fix version updater script

.github/workflows/release.yml, changelogs/config.yaml
Finally figured out why the format of `changelog.yaml` gets messed up from time to time.
I thought `antsichaut` was the culpit but it turns out that `antsibull-changelog` was responsible.
The workflow first passes the changelog to `antsibull-changelog` and then to `antsichaut`.
`antsibull-changelog` rewrites the changelog even if there is no new change but `antsichaut` skips processing it when there are no new changes.
And apparently the yaml that `antsibull-changelog` was putting out was not compatible with `ansible-lint`.
I've proposed fixes over at https://github.com/ansible-community/antsibull-changelog/pull/160 and https://github.com/ansible-community/antsibull-changelog/pull/165
=> fix: make sure antsibull-changelog doesn't offend ansible-lint

.github/workflows/docs-pr.yml, .github/workflows/docs-push.yml
https://github.com/ansible-community/github-docs-build/pull/93
=> skip_changelog(ci): fix docs publish permissions

.github/workflows/ansible-ci.yml, .github/workflows/ansible-test-molecule.yml, .github/workflows/conventional-label.yml
Creates two matrices, one for the roles and another one for all the scenarios within the roles rather than putting all molecule test runs in a single matrix.
This should fix the 256 job limit we hit when attempting to run all the molecule scenarios on all the roles.
=> refactor(ci): split up molecule matrices to avoid job limit 

.github/workflows/ansible-test-integration.yml, .github/workflows/ansible-test-sanity.yml
Previously committed in https://github.com/prometheus-community/ansible/pull/395 but that one needs more work.
=> fix: ansible-community/eol-ansible for 2.9/2.10/2.11 tests

roles/cadvisor/defaults/main.yml, roles/cadvisor/meta/argument_specs.yml, roles/cadvisor/molecule/alternative/molecule.yml, roles/cadvisor/templates/cadvisor.service.j2
Add following
- cadvisor_env_metadata_whitelist
- cadvisor_whitelisted_container_labels
- cadvisor_store_container_labels
Tested with this simple playbook:
```
---
- name: Install cAdvisor
hosts: localhost
become: yes
tasks:
- name: Import cAdvisor role
import_role:
name: cadvisor
vars:
cadvisor_docker_only: true
cadvisor_enable_metrics: [ "cpu", "memory", "network", "oom_event" ]
cadvisor_whitelisted_container_labels: [ "com.docker.compose.oneoff" ]
cadvisor_env_metadata_whitelist: [ "JEKYLL_ENV", "PATH" ]
cadvisor_store_container_labels: false
```
Also tested dropping the options, which is why I decided to explicitly set store_container_labels: true (which is the cadvisor default).
Closes: #403
=> enhancement: adding env/container labels options

.config/molecule/config.yml, meta/runtime.yml, tests/integration/molecule.sh, tests/sanity/ignore-2.17.txt
Fix #386
The last version bump was in https://github.com/prometheus-community/ansible/commit/2e0a30de1aecf46d046e24e2e4a9bff454696305
It is not clear to me, why the version was set down to 2.16.* (from 2.17)
A lot of changes has been between Ansible v2.16.10 and v2.17.3, see https://github.com/ansible/ansible/compare/v2.16.10...v2.17.3
The following ansible version is used with v0.17.1 of the ansible role `prometheus.prometheus`:
```
ansible [core 2.17.3]
config file = None
configured module search path = ['/Users/andy.grunwald/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /opt/homebrew/Cellar/ansible/10.3.0/libexec/lib/python3.12/site-packages/ansible
ansible collection location = …
```
=> minor: bump support for ansible from v2.16.* to v2.17.*

.github/scripts/discover_role_repos.sh, .github/workflows/ansible-ci.yml, roles/fail2ban_exporter/vars/main.yml, roles/smokeping_prober/defaults/main.yml, roles/smokeping_prober/meta/argument_specs.yml
Use [little-timmy](https://github.com/hoo29/little-timmy) for detecting unused variables in the ansible roles.
=> minor(ci): detect unused ansible variables

roles/alertmanager/templates/alertmanager.service.j2
Starting from systemd 239 ([commit link](https://github.com/systemd/systemd/commit/a2d1fb882c4308bc10362d971f333c5031d60069)), it started showing warning about using deprecated path to pidfile in `/var/run` instead of `/run`.
This warning can be seen by launching command `systemctl status alertmanager` or sometring like `journalctl -xeu alertmanager`:
```/etc/systemd/system/alertmanager.service:12: PIDFile= references a path below legacy directory /var/run/, updating /var/run/alertmanager.pid → /run/alertmanager.pid; please update the unit file accordingly.```
=> fix: alertmanager deprecated PIDFile= path warning

roles/_common/tasks/install.yml
This PR adds the `check_mode: false` in the localhost binary cache task.
This is needed because the next task, which downloads the prometheus binary, expects the folder to already be created. Without `check_mode: false`, the task only runs in "simulation" mode and doesn't create the folder.
This code was introduced in the most recent PR #425: https://github.com/prometheus-community/ansible/pull/425/files#diff-c9a8a7fbd7ee9c40d13e4be2e88801e621b943a2246b78ad46b93dc0f7c33971R38
You can see that this task did not exist before: https://github.com/prometheus-community/ansible/pull/425/files#diff-6f9278158452a81913bff59d794daa00e142796b04e75efd873c4a5dbb7f2899L38
Fixes #430
=> fix: add check_mode in localhost binary cache task

tests/integration/molecule.sh
Should fix failing molecule tests on ansible versions 2.9, 2.10, 2.11
=> skip_changelog(ci): pin docker collection on old ansible versions

roles/blackbox_exporter/tasks/configure.yml
Recently, the "Ensure blackbox exporter binary has cap_net_raw capability" task has reported a change for every pipeline run. This PR contains two changes to fix this behavior.
* An [old bug](https://github.com/ansible-collections/community.general/issues/4067) in `community.general.capabilities`, which is caused by naive comparison between requested state and observed state, will indicate a change if the operation is anything besides `=`. This PR changes from `cap_net_raw+ep` to `cap_net_raw=ep` to fix this.
* A [recent PR](https://github.com/prometheus-community/ansible/blob/main/roles/blackbox_exporter/tasks/configure.yml#L22) set `changed_when: "'molecule-idempotence-notest' not in ansible_skip_tags"`, which translates to `changed_when: true`, causing this task to appear as changed no …
=> fix(blackbox_exporter): make capability setting idempotent

roles/_common/tasks/install.yml
I'm trying to install node_exporter on a remote host with a custom `node_exporter_binary_install_dir`.
```
- hosts: all
roles:
- prometheus.prometheus.node_exporter
vars:
node_exporter_binary_local_dir: /home/namsic/downloads/node_exporter-1.6.0.linux-amd64
node_exporter_binary_install_dir: /home/namsic/tmp
```
But when I ran the above playbook, I got the following result:
```
TASK [prometheus.prometheus.node_exporter : Propagate locally distributed node_exporter binary] ****************************************************************************************************************************************************************************************************************************************************************************
fatal: [remote001]: FAILED! => {
"changed": false, …
```
=> fix: make sure binary install dir exists

roles/prometheus/defaults/main.yml, roles/prometheus/meta/argument_specs.yml, roles/prometheus/molecule/alternative/molecule.yml, roles/prometheus/molecule/alternative/prepare.yml, roles/prometheus/molecule/alternative/tests/test_alternative.py, roles/prometheus/molecule/default/prepare.yml, roles/prometheus/molecule/default/tests/test_default.py, roles/prometheus/tasks/configure.yml, roles/prometheus/templates/prometheus.yml.j2
Unfortunately simply rebasing the original PR I missed that the paths in the actual role are wrong. I have now updated them ~and took the chance to also re-use the variable's value for the actual configuration not just the glob for copying~.
//edit: Cannot reuse variable since it would lead to `/etc/prometheus/prometheus/scrapes/...`.
=> fix: scrape config files path

roles/_common/tasks/install.yml
If there is no customized `_common_config_dir` defined, it will raise an error, `FAILED! => {"changed": false, "msg": "useradd: invalid home directory ''\n", "name": "foo", "rc": 3}`.
Here is an Minimal reproducible example
```yaml
- hosts: ubuntu
become: true
vars:
_common_system_user: foo
_common_system_group: foo
_common_config_dir: ""
tasks:
- name: "Create system group {{ _common_system_group }}"
ansible.builtin.group:
name: "{{ _common_system_group }}"
system: true
state: present
become: true
- name: "Create system user {{ _common_system_user }}"
ansible.builtin.user:
name: "{{ _common_system_user }}"
system: true
shell: "/usr/sbin/nologin"
group: "{{ _common_system_group }}"
home: "{{ _common_config_dir | default('/') }}"
create_home: false
become: true
```
```shell
❯ …
```
=> bugfix: update default home directory

roles/_common/meta/argument_specs.yml, roles/_common/tasks/preflight.yml, roles/_common/vars/main.yml, roles/alertmanager/tasks/preflight.yml, roles/bind_exporter/tasks/preflight.yml, roles/blackbox_exporter/tasks/preflight.yml, roles/chrony_exporter/tasks/preflight.yml, roles/fail2ban_exporter/tasks/preflight.yml, roles/influxdb_exporter/tasks/preflight.yml, roles/ipmi_exporter/tasks/preflight.yml, roles/memcached_exporter/tasks/preflight.yml, roles/mongodb_exporter/tasks/preflight.yml, roles/mysqld_exporter/tasks/preflight.yml, roles/nginx_exporter/tasks/preflight.yml, roles/node_exporter/tasks/preflight.yml, roles/postgres_exporter/tasks/preflight.yml, roles/process_exporter/tasks/preflight.yml, roles/prometheus/tasks/preflight.yml, roles/pushgateway/tasks/preflight.yml, roles/redis_exporter/tasks/preflight.yml, roles/smartctl_exporter/tasks/preflight.yml, roles/smokeping_prober/tasks/preflight.yml, roles/snmp_exporter/tasks/preflight.yml, roles/systemd_exporter/tasks/preflight.yml
If this proposal is accepted, I'll update all other roles
=> refactor: move naive assertion to common role

roles/nvidia_gpu_exporter/tasks/preflight.yml
The nvidia_gpu_exporter role slipped through #443
=> refactor(nvidia_gpu_exporter): move naive assertion to common role

.github/scripts/discover_role_repos.sh
Fix syntax of split to correctly select list item.
* Add some extra stderr debugging logs.
* Skip the `_common` role.
* Skip roles where the repo is missing.
=> skip_changelog: Fix role repo discovery

roles/prometheus/defaults/main.yml, roles/prometheus/meta/argument_specs.yml, roles/prometheus/molecule/agentmode/tests/test_agentmode.py, roles/prometheus/molecule/default/tests/test_default.py, roles/prometheus/tasks/configure.yml, roles/prometheus/templates/prometheus.service.j2
Update prometheus role for 3.0.0.
* Update argument_specs.yml to reflect support of 3.x.
* Skip console templates on 3.x.
Fixes: https://github.com/prometheus-community/ansible/issues/460
=> feat: Support Prometheus 3.0

.config/molecule/config.yml
Test if rolling back almalinux fixes build issues.
=> skip_changelog: Pin almalinux to old container images

.github/workflows/publish.yml
Switch over to ansible community managed github action rather than manually installing ansible and building the collection which is currently broken in our workflow: https://github.com/prometheus-community/ansible/actions/runs/12636461860/job/35208578989
=> skip_changelog(ci): fix failing collection build on publish

roles/_common/tasks/install.yml
GitLab has recently started using 308 redirects for release assets, which causes compatibility issues with older versions of Ansible and Python. ~~Our options for resolving this are limited, so the best solution for now is to allow the checksum download task to proceed with a warning. Unfortunately, this has the side effect of disabling checksum verification when the warning is triggered, but AFAIK it remains the only workable approach at this time.~~
To mitigate the issue I have switched the tasks from using the `get_url` module and the `url` lookup to use the `uri` module instead as it supports configuring which http status codes should be considered as successful and also enables redirect behavior customization.
See more here: …
=> fix: unsupported http response code issues on older ansible/python versions

.github/workflows/release.yml
I belive `ansible-base` is obsolete and has been replaced with `ansible-core`. This should fix Python 3.12 compatibility.
Fixes: https://github.com/prometheus-community/ansible/issues/522
=> skip_changelog: Switch release to ansible-core

roles/_common/tasks/install.yml
This PR adds the `check_mode: false` in the fetch checksum task.
This is needed because the next task, which parses the checksum list, expects the checksum files to already be downloaded. Without `check_mode: false`, the task only runs in "simulation" mode and doesn't download the files.
This "bug" was introduced during a refactor: https://github.com/prometheus-community/ansible/commit/6209b53314d61b375578572e9b4df7e120ce3066
Without `check_mode: false`:
```
TASK [prometheus.prometheus._common : Fetch checksum list for prometheus-2.48.1.linux-amd64.tar.gz] ***********************************************************************
skipping: [node]
TASK [prometheus.prometheus._common : Parse checksum list for prometheus-2.48.1.linux-amd64.tar.gz] …
```
=> fix: add check_mode to the checksum task

roles/_common/tasks/install.yml
During the common install tasks, we download and unpack the binary to install on localhost and eventually upload it to each host (among many other things). Currently the "unpack" step, which extracts the gzipped tar archive, is perform N times if there are N hosts in the inventory, but the target directory (something like
/tmp/node_exporter-linux-arm64/1.8.2) is the same for every host with the same architecture.
This means that all the unarchive tasks are extracting in parallel in an unsynchronized manner to the same directory. It a miracle that this works, but at least usually it like it does, but sometimes tar will complain about a missing file, failing the install. I've confirmed locally that this is due to the race described above.
To fix this, we use `throttle: 1` on the unpack …
=> fix: use throttle: 1 for localhost unarchive

roles/prometheus/templates/prometheus.service.j2
Small PR to fix identation of argument in prometheus.service file
Before:
```
...
--storage.tsdb.retention.size=0 \
--web.config.file=/etc/prometheus/web_config.yml \
--web.console.libraries=/etc/prometheus/console_libraries \
...
```
After:
```
...
--storage.tsdb.retention.size=0 \
--web.config.file=/etc/prometheus/web_config.yml \
--web.console.libraries=/etc/prometheus/console_libraries \
...
```
=> fix: identation in service file

roles/alertmanager/tasks/main.yml
Only in the `alertmanager` was there no written setting that would be enabled on boot.
```bash
$ for f in roles/*/tasks/main.yml; do grep -q 'enabled: true' $f || echo $f; done
roles/alertmanager/tasks/main.yml
```
=> fix: add `enabled: true` to alertmanager

.github/workflows/ansible-ci.yml, .github/workflows/ansible-test-integration.yml, .github/workflows/ansible-test-molecule.yml, .github/workflows/ansible-test-sanity.yml, .github/workflows/conventional-label.yml, .github/workflows/docs-pr.yml, .github/workflows/docs-push.yml, .github/workflows/publish.yml, .github/workflows/release.yml, .github/workflows/version_bumper.yml
Update various github actions to pin SHA for supply chain security.
* Replace `tj-actions/changed-files` due to CVE-2023-51664.
=> skip_changelog: Update GitHub actions

.config/molecule/config.yml
Ignore Ansible 2.18 on Ubuntu 20.04 as it appears to have broken Python 3.8 support.
=> skip_changelog: Update supported testing

roles/snmp_exporter/tasks/main.yml
Added when clause to Ensure snmp_exporter service is started and enabled to not run in check mode
https://github.com/prometheus-community/ansible/issues/609
=> fix(snmp_exporter): Added when clause to snmp_exporter role

.github/workflows/conventional-label.yml
Fixes issues such as:
```
Run git diff --name-only 7d82cd8aaec22f4ecb8cb7ef9d45dde9556c91cf -r | grep -E '^roles/' | cut -f 1-2 -d'/' | sort -u >> "$GITHUB_OUTPUT"
fatal: bad object 7d82cd8aaec22f4ecb8cb7ef9d45dde9556c91cf
```
=> skip_changelog(ci): fix changed role detection script
