prometheus-community/ansible

MAINTAINERS.md
Signed-off-by: SuperQ <superq@gmail.com>
=> Add maintainers file.

galaxy.yml, roles/alertmanager/molecule/alternative/prepare.yml, roles/alertmanager/tasks/configure.yml, roles/alertmanager/tasks/install.yml, roles/alertmanager/tasks/preflight.yml, roles/blackbox_exporter/tasks/configure.yml, roles/blackbox_exporter/tasks/install.yml, roles/node_exporter/molecule/alternative/prepare.yml, roles/node_exporter/tasks/configure.yml, roles/node_exporter/tasks/install.yml, roles/node_exporter/tasks/preflight.yml, roles/prometheus/molecule/alternative/prepare.yml, roles/prometheus/tasks/configure.yml, roles/prometheus/tasks/install.yml, roles/prometheus/tasks/preflight.yml, roles/snmp_exporter/tasks/configure.yml, roles/snmp_exporter/tasks/install.yml, roles/snmp_exporter/tasks/preflight.yml
Fixes fqcn's that had slipped in as module parameters and other minor lint fixes.
fixes #7
=> fix: fqcn in module params

.github/workflows/ansible-ci.yml, .github/workflows/conventional-label.yml
Accidentally only fixed one workflow trigger in #29 , this fixes the rest of the workflows.
=> fix: writable token in all pull request workflows

.github/workflows/publish.yml
Use the full semver version for the publish action.
=> packaging: Fix publish action version

roles/alertmanager/tasks/selinux.yml, roles/node_exporter/tasks/selinux.yml
Signed-off-by: Valentin Delaye [jonesbusy@gmail.com](mailto:jonesbusy@gmail.com)
=> fix: Fix typo on Install selinux python packages for RedHat family

tests/integration/molecule.sh
Installs missing test requirements on ansible 2.12+
=> test: fix: 2.12+ test requirements install

.github/workflows/version_bumper.yml, roles/alertmanager/defaults/main.yml, roles/blackbox_exporter/defaults/main.yml, roles/node_exporter/defaults/main.yml, roles/prometheus/defaults/main.yml, roles/snmp_exporter/defaults/main.yml, roles/systemd_exporter/defaults/main.yml, version_updater.sh
Add a script and workflow to automatically check for upstream releases and create PRs to update the associated role.
=> skip-release: Add workflow to auto-update versions

.github/workflows/docs-pr.yml, .github/workflows/docs-push.yml, roles/alertmanager/meta/argument_specs.yml
Using worklows from: https://github.com/ansible-community/github-docs-build
See: https://github.com/ansible-community/github-docs-build/wiki/Getting-started-with-GitHub-Pages
=> docs: add workflow for auto generating ansible docs

.github/workflows/version_bumper.yml
Fix version bumper step, needs a `run` when not using `uses`.
=> fix: version bumper action

changelogs/fragments/fix86_apply_tags.yml, roles/alertmanager/tasks/main.yml, roles/blackbox_exporter/tasks/main.yml, roles/mysqld_exporter/tasks/main.yml, roles/node_exporter/tasks/main.yml, roles/prometheus/tasks/main.yml, roles/snmp_exporter/tasks/main.yml, roles/systemd_exporter/tasks/main.yml
This is a PR to fix #86
I think `import_tasks` should be prefered. But I don't want to impose my choice.
=> fix: tags support for included tasks

.github/scripts/discover_role_repos.sh, .github/workflows/version_bumper.yml
Use the correct syntax for getting the output from a workflow job.
=> skip_changelog: Fix workflow outputs syntax

.github/workflows/version_bumper.yml
Use full checkout to make sure we get the correct main history.
* Shorten name to make Actions page easier to read.
=> fix: Checkout full branch for version updates

.github/workflows/version_bumper.yml
=> skip_changelog: Fix typo in version bumper

.github/scripts/version_updater.sh
Add DCO signoff for prombot PRs.
=> skip_changelog: Add prombot DCO

.github/release-drafter.yml, .github/workflows/conventional-label.yml, .yamllint.yml
Adjust yaml linting rules to fix non-issues with GitHub actions yaml.
=> skip_changelog: Update yaml linting

roles/smokeping_prober/meta/argument_specs.yml
Add missing arguments spec entries.
=> docs(smokeping_prober): Update arguments specs

.github/workflows/ansible-test-integration.yml
Hopefully got it right this time
=> skip_changelog: fix ansible-test ci coverage input 

roles/alertmanager/tasks/install.yml, roles/chrony_exporter/tasks/install.yml, roles/mysqld_exporter/tasks/install.yml, roles/node_exporter/tasks/install.yml, roles/pushgateway/tasks/install.yml, roles/smokeping_prober/tasks/install.yml
Update names to be consistent, reflect task block.
=> skip_changelog: Fixup install task names

.github/workflows/release.yml, changelogs/changelog.yaml
Hopeful I figured out and were able to fix the changelog.yaml screwup once and for all
=> skip_changelog: restore changelog and test changelog generator fix

roles/memcached_exporter/defaults/main.yml, roles/memcached_exporter/meta/argument_specs.yml, roles/memcached_exporter/templates/memcached_exporter.service.j2
In my installation memcached doesn't listen on ip 127.0.0.1 this modification allows to specify a custom ip if needed
=> patch: added the ability to choose which ip to connect

roles/prometheus/defaults/main.yml, roles/prometheus/meta/argument_specs.yml, roles/prometheus/tasks/configure.yml, roles/prometheus/tasks/install.yml, roles/prometheus/templates/prometheus.yml.j2
Add support for scrape_config_files (fixes #145)
Attention: This is merely a rebase of #292.
=> feat: Added prometheus scrape_config_files support

roles/_common/tasks/install.yml
=> fix: don't modify system user or group if they already exist

roles/_common/tasks/install.yml
=> fix:  prevent local binary cache creation with elevated privileges

roles/_common/tasks/install.yml
=> fix: remove unused variable

roles/nvidia_gpu_exporter/README.md, roles/nvidia_gpu_exporter/defaults/main.yml, roles/nvidia_gpu_exporter/handlers/main.yml, roles/nvidia_gpu_exporter/meta/argument_specs.yml, roles/nvidia_gpu_exporter/meta/main.yml, roles/nvidia_gpu_exporter/molecule/alternative/molecule.yml, roles/nvidia_gpu_exporter/molecule/alternative/tests/test_alternative.py, roles/nvidia_gpu_exporter/molecule/default/molecule.yml, roles/nvidia_gpu_exporter/molecule/default/tests/test_default.py, roles/nvidia_gpu_exporter/molecule/latest/molecule.yml, roles/nvidia_gpu_exporter/molecule/latest/tests/test_latest.py, roles/nvidia_gpu_exporter/tasks/main.yml, roles/nvidia_gpu_exporter/tasks/preflight.yml, roles/nvidia_gpu_exporter/templates/nvidia_gpu_exporter.service.j2, roles/nvidia_gpu_exporter/vars/main.yml, tests/integration/targets/molecule-nvidia_gpu_exporter-alternative/runme.sh, tests/integration/targets/molecule-nvidia_gpu_exporter-default/runme.sh, tests/integration/targets/molecule-nvidia_gpu_exporter-latest/runme.sh
Too many labels are added in #380 , there are much more ci jobs run unexpectedly.
So a new PR is created
=> feat: Add nvidia_gpu_exporter

.config/molecule/config.yml
=> refactor: use molecule containers from ghcr to avoid rate limit

roles/prometheus/tasks/configure.yml
=> fix: use elevated permissions for removing scrapes dir

.github/workflows/ansible-ci.yml
* Pin release version for supply chain security.
* Include requirements.yml.
=> skip_changelog: Update ansible-lint action
